default:
	make -C EngineAPI_Soloud/
	make -C Krilloud_static/
	make -C Krilloud_Client_API_static/
	make -C Krilloud_Clien_API_DLL/

clean:
	make -C EngineAPI_Soloud/ clean
	make -C Krilloud_static/ clean
	make -C Krilloud_Client_API_static/ clean
	make -C Krilloud_Clien_API_DLL/ clean
